// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDwNMflbnfSMUsNtG0jACGCTLo8S7fd8o',
    appId: '1:451783510501:web:4832c583974a3413d2870c',
    messagingSenderId: '451783510501',
    projectId: 'push-notification-9b465',
    authDomain: 'push-notification-9b465.firebaseapp.com',
    storageBucket: 'push-notification-9b465.appspot.com',
    measurementId: 'G-4E3QXGH0FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKliJjEuqtD1-KMlp_VS_GZZW0-Ru8B4k',
    appId: '1:451783510501:android:d2a13c1f630b2ee7d2870c',
    messagingSenderId: '451783510501',
    projectId: 'push-notification-9b465',
    storageBucket: 'push-notification-9b465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOnULAwlYIfscoDtDKTTydCxn3uBrUdM8',
    appId: '1:451783510501:ios:6b88fa36b364a959d2870c',
    messagingSenderId: '451783510501',
    projectId: 'push-notification-9b465',
    storageBucket: 'push-notification-9b465.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOnULAwlYIfscoDtDKTTydCxn3uBrUdM8',
    appId: '1:451783510501:ios:676cbc65da073640d2870c',
    messagingSenderId: '451783510501',
    projectId: 'push-notification-9b465',
    storageBucket: 'push-notification-9b465.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
